# Generated by Django 4.0.1 on 2022-01-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addedReposModel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('count', models.BigIntegerField()),
                ('unique', models.BigIntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repository')),
            ],
            options={
                'verbose_name_plural': 'RepositoryViews',
                'db_table': 'repositoriy_views',
                'ordering': ['timestamp'],
            },
        ),
    ]
